<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Test.Common.Application\Test.Common.Application.csproj" />
    <ProjectReference Include="..\Module.Playlist.Domain\Module.Playlist.Domain.csproj" />
  </ItemGroup>

</Project>
