<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Luftborn_Task.UnitTests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Playlists\Module.Playlist.Application\Module.Playlist.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Playlists\Module.Playlist.Domain\Module.Playlist.Domain.csproj" />
  </ItemGroup>

</Project>
