
services:
  Test.api:
    image: ${DOCKER_REGISTRY-}lefbornapi
    container_name: Lefborn.Api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    depends_on:
      - Test.database
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: Host=Lefborn.Database;Port=5432;Database=Test;Username=postgres;Password=postgres;Include Error Detail=true
    ports:
      - 5000:8080
      - 5001:8081

  Test.database:
    image: postgres:16-alpine
    container_name: Lefborn.Database
    environment:
      POSTGRES_DB: Test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  postgres_data:



      
