<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Test.Common.Domain\Test.Common.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="FluentValidator" Version="2.0.4" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>

</Project>
