<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Test.Common.Application\Test.Common.Application.csproj" />
    <ProjectReference Include="..\..\..\Common\Test.Common.Domain\Test.Common.Domain.csproj" />
    <ProjectReference Include="..\..\Users\Module.Users.PublicApi\Module.Users.PublicApi.csproj" />
    <ProjectReference Include="..\Module.Songs.Domain\Module.Songs.Domain.csproj" />
  </ItemGroup>

</Project>
