<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Test.Common.Application\Test.Common.Application.csproj" />
    <ProjectReference Include="..\..\Playlists\Module.Playlist.PublicApi\Module.Playlist.PublicApi.csproj" />
    <ProjectReference Include="..\..\Songs\Module.Songs.PublicApi\Module.Songs.PublicApi.csproj" />
    <ProjectReference Include="..\Module.Users.Domain\Module.Users.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
  </ItemGroup>

</Project>
