<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Test.Common.Infrastructure\Test.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\Module.Users.Application\Module.Users.Application.csproj" />
    <ProjectReference Include="..\Module.Users.Domain\Module.Users.Domain.csproj" />
    <ProjectReference Include="..\Module.Users.Presentation\Module.Users.Presentation.csproj" />
    <ProjectReference Include="..\Module.Users.PublicApi\Module.Users.PublicApi.csproj" />
  </ItemGroup>

</Project>
